nodeLinker: node-modules

# If true, Yarn will always send the authentication credentials when making a request to the registries. This typically shouldn't be needed
npmAlwaysAuth: false

# If true (by default detects terminal capabilities), Yarn will format its pretty-print its output by using colors to differentiate important parts of its messages.
enableColors: true

# Defines the default access to use when publishing packages to the npm registry. Valid values are public and restricted, but restricted usually requires to register for a paid plan (this is up to the registry you use).
npmPublishAccess: "public"

npmRegistryServer: "https://registry.npmjs.org/"

yarnPath: .yarn/releases/yarn-3.1.1.cjs
